server:
  port: ${vcap.application.port:1113}
  
ribbon:
  readTimeout: 500000
  connectTimeout: 500000   

logging:
  level:
    root: WARN  
  
---   
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.owpeurekaservice.credentials.url:http://127.0.0.1:8761}/eureka/
      
 